name: medai_app
description: A Flutter mobile app for medical report understanding.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7

flutter:
  uses-material-design: true
